### ISSUE TITLE
HEAT - 24 hour statistics

### ISSUE THREAD

**Issue by geho2** [Heat-Ledger-Ltd/heat-ui#17]
The 24 hour statistics in heatwallet (upper right hand corner) does not update correctly, even if there has been many transactions. Statistics below for HEAT/EUR market on testnet:
[https://dl.dropboxusercontent.com/s/f4ans293s3e3tgh/heat-24-stats.jpg](https://dl.dropboxusercontent.com/s/f4ans293s3e3tgh/heat-24-stats.jpg)

**Comment by dmdeklerk** [comment]
Server related. Created copy of issue in server code issue tracker

**Comment by resultingforce** [comment]
Seems solved,  look at the https://heatwallet.com/#/trader/5592059897546023466/0
