### ISSUE TITLE
Pop Up Warning 

### ISSUE THREAD

**Issue by spyderspyder** [Heat-Ledger-Ltd/heat-ui#20]
This would be good for anytime something costs more than the standard .01 HEAT, but I noticed that when I created an asset and when I created a market in the AE it deducted 10 HEAT for each.  A pop up warning/confirmation to proceed stating the fee to the user would be a nice feature to have so users do no get hit with fees they are unaware of or have forgotten about.

**Comment by dmdeklerk** [comment]
Good point.

**Comment by resultingforce** [comment]
Seems that is done already, see at bottom

![image](https://user-images.githubusercontent.com/15869088/33335215-795240c2-d47d-11e7-992d-d8364926393f.png)

![image](https://user-images.githubusercontent.com/15869088/33335239-8af7c3c4-d47d-11e7-8f56-c001224d1c00.png)

![image](https://user-images.githubusercontent.com/15869088/33335289-ae7cc510-d47d-11e7-99b7-00f41e09efe7.png)
