### ISSUE TITLE
Clickable balances

### ISSUE THREAD

**Issue by geho2** [Heat-Ledger-Ltd/heat-ui#24]
It would be nice if clicking on the HEAT or BTC balance (upper left corner in the Asset Exchange, HEAT/BTC market) would automatically transfer the amount to "Amount HEAT" or "Total BTC" in the Buy/Sell fields. That would save some copy+paste when, for example, all BTC is put into a Buy order.

**Comment by ahatolkar-grepruby** [comment]
Attended
