### ISSUE TITLE
Add Last-Modified to index.html to force reload of new UI versions

### ISSUE THREAD

**Issue by fitcoin** [Heat-Ledger-Ltd/heat-ui#25]
Add this line

`<meta http-equiv="Last-Modified" content="Fri 07 Apr 2017 21:00:00">`

before     <title>HEAT</title>

Adjust content in that exact format to match with the time of deployment of each new client version on heatwallet.com and downloadable.

**Comment by dmdeklerk** [comment]
done https://github.com/Heat-Ledger-Ltd/heat-ui/commit/f723454db0d1f7ea5dfad4aac9520d2ec9d35e02
