### ISSUE TITLE
Withdraw Ignis

### ISSUE THREAD

**Issue by renkcub** [Heat-Ledger-Ltd/heat-ui#30]
I purchased your pre-sold IGNIS with the promise of being able to withdraw shortly (<1 month) after the chain launch. Now I can't even get a dev response. Can you please add support for this today or exchange to me directly today OTC?

**Comment by dmdeklerk** [comment]
Please contact the asset issuer.
This issue tracker is meant for issues relating to the heat-ui codebase.
Closing this issue.

**Comment by renkcub** [comment]
Isn't heat the asset issuer?
